spring:
  application:
    name: spring-boot-template-dev
  datasource:
    url: jdbc:mysql://localhost:3306/employee_dev_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: dev_employee_user
    password: dev_employee_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
