# Üretim ortamı için replica sayısı
replicaCount: 1  # Örneğin: 3, 5, 10 gibi değerler kullanılabilir

image:
  # Üretim image'ınızın bulunduğu Docker repository
  repository: your-docker-repo/spring-boot-template-prod
  # Uygulamanızın sürüm numarası, örn. "1.0.0", "1.0.1" vs.
  tag: "1.0.0"
  # Image çekme politikası: 
  # - IfNotPresent: Image yerel olarak bulunuyorsa çekilmez.
  # - Always: Her dağıtımda image çekilir.
  # - Never: Hiç çekilmez.
  pullPolicy: IfNotPresent

service:
  # Kubernetes servis tipi; Üretimde genellikle LoadBalancer kullanılır,
  # diğer seçenekler: ClusterIP, NodePort, ExternalName.
  type: LoadBalancer
  # Servisin dışa açılacağı port.
  port: 8080

ingress:
  enabled: true
  # Ingress için kullanılacak sınıf. Örneğin, "nginx", "traefik" gibi.
  className: "nginx"
  annotations:
    # Ingress'in hangi controller tarafından yönetileceğini belirler.
    kubernetes.io/ingress.class: "nginx"
    # SSL yönlendirmesi için: "true" ise HTTP istekleri HTTPS'e yönlendirilir.
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: prod.example.com  # Üretim ortamına ait domain adı.
      paths:
        - path: /           # Trafiğin yönlendirileceği URL yolu.
          # Path tipi: 
          # - Prefix: Belirtilen path ile başlayan tüm istekler,
          # - Exact: Tam eşleşme gerektirir,
          # - ImplementationSpecific: Ingress Controller'a bağlı olarak farklı davranış.
          pathType: Prefix

spring:
  profiles:
    active: prod  # Aktif Spring profili; Örneğin: dev, test, prod
  datasource:
    # Üretim veritabanı bağlantı URL'si. Prod-db-host yerine gerçek hostname veya IP kullanılmalı.
    url: jdbc:mysql://prod-db-host:3306/employee_db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
    # Veritabanı kullanıcı adı
    username: prod_employee_user
    # Veritabanı şifresi
    password: prod_employee_pass

resources:
  limits:
    # Konteynerin maksimum CPU limiti, örn: "500m" = 0.5 CPU
    cpu: "500m"
    # Konteynerin maksimum bellek limiti, örn: "512Mi"
    memory: "512Mi"
  requests:
    # Konteyner için minimum CPU isteği
    cpu: "250m"
    # Konteyner için minimum bellek isteği
    memory: "256Mi"
